services:
  eureka-server:
    build:
      context: eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - backend

  api-gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - backend

  # Add other microservices similarly

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - backend

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: v_engine
      POSTGRES_USER: v_engine
      POSTGRES_PASSWORD: v_engine
    ports:
      - "5432:5432"
    networks:
      - backend

networks:
  verbose-engine-backend:
    driver: bridge